#!/bin/sh
if command -v qmd > /dev/null 2>&1; then
  qmd update --collection knowledge
  QMD_EMBED_MODEL="hf:Qwen/Qwen3-Embedding-0.6B-GGUF/Qwen3-Embedding-0.6B-Q8_0.gguf" qmd embed --collection knowledge
else
  echo "qmd not found."
fi
